### PR TITLE
Moved Icon ref

### PR DESCRIPTION
**Pull request by mariomurrent-softwaresolutions**
This is about Issue #5

### CODE REVIEW

**Comment by kuraydev** [comment]
@mariomurrent-softwaresolutions Really? Does just this solve that issue? :D

**Comment by mariomurrent-softwaresolutions** [comment]
Actually yes 😊😛

**Review by kuraydev — APPROVED** [review]

**Comment by mariomurrent-softwaresolutions** [comment]
I also tested it in my app and everything works fine

**Comment by kuraydev** [comment]
@mariomurrent-softwaresolutions Thank you so much, man!

**Pull request merged**
