### PR TITLE
Added property to be able to set the input readonly

### PR DESCRIPTION
**Pull request by mariomurrent-softwaresolutions**

### CODE REVIEW

**Comment by kuraydev** [comment]
Actually I can accept this PR but you broke the styling and its really hard to review it. Can you please fix the broken styling and let me test it and accept this PR :) 

Also @ts-ignore is redundant

@mariomurrent-softwaresolutions Thank you for the contribution

**Comment by mariomurrent-softwaresolutions** [comment]
Ah you mean the code style/code format?

**Comment by mariomurrent-softwaresolutions** [comment]
@WrathChaos Done and sorry for the formatting chaos.

**Review by kuraydev — APPROVED** [review]
@mariomurrent-softwaresolutions Approved! Thank you for the contribution :)

Just to let you know, do not increase the library's version. The author should handle it :)

**Pull request merged**
