### PR TITLE
Bugfix/fix animated arrow

### PR DESCRIPTION
**Pull request by mariomurrent-softwaresolutions**
Move the set state call to an earlier position so that is does not clash with the animation.

Otherwise there are some edge cases, where the icon does not match with the opened/close state of the dropdown.

This was also a problem for #5. So only moving the iconRef did not help

### CODE REVIEW

**Comment by kuraydev** [comment]
Thank you @mariomurrent-softwaresolutions 
I will take a look at it and test it today :)

**Comment by mariomurrent-softwaresolutions** [comment]
Any updates on this one? :)

**Review by kuraydev — APPROVED** [review]

**Comment by kuraydev** [comment]
Sorry for late release :) 
Thank you so much for contribution tho @mariomurrent-softwaresolutions 

### [Release 0.4.1](https://github.com/WrathChaos/react-native-single-select/releases/tag/0.4.1)

**Comment by mariomurrent-softwaresolutions** [comment]
No worries :) Everything is fine. 
Finally I can remove my patch-package.

Thx for review and merging

**Pull request merged**
